/*
    Copyright © 2010 par Marc Sibert

    This file is part of LIBOSM

    LIBOSM is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    LIBOSM is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with LIBOSM.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * \file
 * \author Marc Sibert
 */

// Class automatically generated by Dev-C++ New Class wizard

#include "element.h" // class's header file
#include "osm_exception.h"
#include <iomanip>

void Element::setAttribut(const string& aKey, const string& aValue)
{
    istringstream iss(aValue);
    if (aKey == "visible") iss >> fVisible;
    else if (aKey == "version") iss >> fVersion;
    else if (aKey == "changeset") iss >> fChangeset;
    else if (aKey == "timestamp") iss >> fTimestamp;
    else Top::setAttribut(aKey, aValue);
}

ostream& Element::afficher(ostream& aStream) const
{
    Top::afficher(aStream);
    if (!fVisible)
        aStream << "visible=\"" << (fVisible ? "true" : "false") << "\" ";
    if (fVersion)
        aStream << "version=\"" << fVersion << "\" ";
    if (!fChangeset)
        aStream << "changeset=\"" << fChangeset << "\" ";
    if (!fTimestamp.iso8601().empty())
        aStream << "timestamp=\"" << fTimestamp.iso8601() << "\" ";
    return aStream;
}

bool Element::operator==(const Element& aElement) const
{
    if (!Top::operator==(aElement)) return false;
// Attributs identiques ?
    if ((fVisible != aElement.fVisible) ||
		(fVersion != aElement.fVersion) ||
		(fChangeset != aElement.fChangeset) ||
        (fTimestamp != aElement.fTimestamp)) return false;
// Sinon ce sont les mêmes !
    return true;
}
