/*
    Copyright © 2010 par Marc Sibert

    This file is part of LIBOSM

    LIBOSM is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    LIBOSM is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with LIBOSM.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * \file
 * \author Marc Sibert
 */

// Class automatically generated by Dev-C++ New Class wizard

#include "node.h" // class's header file
#include <iomanip>

void Node::setAttribut(const string& aKey, const string& aValue)
{
    istringstream iss(aValue);
    if (aKey == "lat") iss >> fLatitude;
    else if (aKey == "lon") iss >> fLongitude;
    else Element::setAttribut(aKey, aValue);
}

const string Node::NOM = "node";

ostream& operator<<(ostream& aStream, const Node& aNode)
{
    aStream << "\t<node ";
    Element(aNode).afficher(aStream);
    aStream << setprecision(10) << "lat=\"" << aNode.latitude() << "\"";
    aStream << " lon=\"" << aNode.longitude() << "\">" << endl;
    Element(aNode).afficherTags(aStream);
    aStream << "\t</node>" << endl;
    return aStream;
}

