/*
    Copyright © 2010 par Marc Sibert

    This file is part of LIBOSM

    LIBOSM is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    LIBOSM is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with LIBOSM.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * \file
 * \author Marc Sibert
 */

// Class automatically generated by Dev-C++ New Class wizard

#include "relation.h" // class's header file

const string Relation::NOM = "relation";

ostream& Relation::afficherMembers(ostream& aStream) const
{
    for (list<Member>::const_iterator i = fMembers.begin(); i != fMembers.end(); ++i)
        aStream << *i << endl;
    return aStream;
}

void Relation::addMember(const Member& aMember)
{
    fMembers.push_back(aMember);
}

ostream& Relation::afficher(ostream& aStream) const
{
    aStream << "\t<relation ";
    Element::afficher(aStream);
    aStream << ">" << endl;
    Element::afficherTags(aStream);
    afficherMembers(aStream);
    aStream << "\t</relation>" << endl;
    return aStream;
}
